[package]
name = "probe-opencollection"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
atomic-write-file = "0.3.1"
fs4 = "1.1.0"
probe-core = { path = "../core" }
serde = { version = "1", features = ["derive"] }
serde_yaml_ng = "0.10"

[lints]
workspace = true
