# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

reviews:
  profile: "assertive"
  high_level_summary: true
  poem: false
  request_changes_workflow: false

  auto_review:
    enabled: true
    drafts: false
    auto_incremental_review: true
    base_branches:
      - ".*"

chat:
  auto_reply: true