[package]
name = "probe-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
base-gpui = { git = "https://github.com/LukeTandjung/base-gpui", rev = "ceb5153aa3ee561010b2b33c13af6793d56eddb6" }
gpui = { version = "0.2.2", git = "https://github.com/zed-industries/zed", rev = "59b2ebf10351b5c0b5cd4403f01ed0460eeec06d" }
probe-core = { path = "../core" }

[target.'cfg(target_os = "macos")'.dependencies]
gpui_platform = { version = "0.1.0", git = "https://github.com/zed-industries/zed", rev = "59b2ebf10351b5c0b5cd4403f01ed0460eeec06d", features = ["font-kit", "runtime_shaders"] }

[target.'cfg(target_os = "windows")'.dependencies]
gpui_platform = { version = "0.1.0", git = "https://github.com/zed-industries/zed", rev = "59b2ebf10351b5c0b5cd4403f01ed0460eeec06d" }

[target.'cfg(target_os = "linux")'.dependencies]
gpui_platform = { version = "0.1.0", git = "https://github.com/zed-industries/zed", rev = "59b2ebf10351b5c0b5cd4403f01ed0460eeec06d", features = ["wayland", "x11"] }

[lints]
workspace = true
